name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install Dependencies
        uses: pnpm/action-setup@v3
        with:
          version: latest
          run_install: true
      - name: Lint
        run: |
          export NODE_OPTIONS=--max_old_space_size=4096
          pnpm lint

  test-unit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install Dependencies
        uses: pnpm/action-setup@v3
        with:
          version: latest
          run_install: true
      - name: Unit Tests
        run: pnpm test

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install Dependencies
        uses: pnpm/action-setup@v3
        with:
          version: latest
          run_install: true
      - name: Build
        run: pnpm build
